apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: web
          image: majid36344/hello-nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
